#pragma once

//SERVER:
#define PORT 1267

//MSG:
#define MSG_SEPARATOR "###"
#define BUFFER_SIZE 128
#define SERVER_RESPONSE_CODE_SIZE 4

//PROTOCOL:
#define INVALID_CODE 0001
#define NO_CODE 0002
#define FORCED_DISCONNECT 0000
#define OPERATION_FAILED_LOW_AUTHORITY 0003

//Authority:
#define GUEST_AUTH 1
#define USER_AUTH 2
#define STUDENT_AUTH 3
#define AUTHORISED_STUDENT_AUTH 4
#define TEACHER_AUTH 5
#define ADMIN_AUTH 6

//Account:
#define GUEST_SIGN_IN 202
#define SIGN_IN 200
#define SIGN_OUT 201
#define SIGN_UP 203
#define SIGN_IN_SUCCESS 1020
#define SIGN_IN_FAIL 1021
#define SIGN_IN_FAIL_USER_ALREADY_CONNECTED 1022
#define SIGN_UP_SUCCESS 1040
#define SIGN_UP_FAIL_PASS_ILLEGAL 1041
#define SIGN_UP_FAIL_EMAIL_TAKEN 1042
#define SIGN_UP_FAIL_EMAIL_INVALID 1043
#define SIGN_UP_FAIL 1044

//Sensors:
#define GET_SENSOR_VALUES_BY_DATE 302
#define GET_SERNSOR_VAL 300
#define RETURN_SENSOR_VAL 1050
#define RETURN_SENSOR_VAL_FAIL 1051
#define RETURN_SENSOR_VALUES_BY_DATE 1054
#define RETURN_SENSOR_VALUES_BY_DATE_FAIL 1055
#define NO_SENSOR_VALUES_IN_CHOSEN_DATE 1056
#define REFRESH_SERNSOR_VAL 301
#define REFRESH_SERNSOR_VAL_SUCCESS 1052
#define REFRESH_SERNSOR_VAL_FAIL 1053

//Watering:
#define GET_WATERING_HUMID_VAL 400
#define SET_WATERING_HUMID_VAL 401
#define RETURN_WATERING_HUMID_VAL_SECCESS 1060
#define RETURN_WATERING_HUMID_VAL_FAIL 1061
#define WATERING_HUMID_VAL_SUCCESSFULY_SET 1062
#define WATERING_HUMID_VAL_FAILED_TO_SET 1063

//Pollination
#define GET_POLLINATIONS_DETAILS_BY_DATE 500
#define SET_NEW_POLLINATION 501
#define RETURN_POLLINATIONS_DETAILS 1070
#define RETURN_POLLINATIONS_DETAILS_FAIL 1071
#define NEW_POLLINATION_SUCCESSFULY_SET 1072
#define FAILED_TO_SET_NEW_POLLINATION 1073
#define NO_POLLINATIONS_IN_CHOSEN_DATE 1074

//Camera
#define GET_LAST_PICTURE 600
#define GET_PICTURE_BY_DATE 601
#define GET_NEW_PICTURE 602
#define RETURN_PICTURE 1080
#define RETURN_PICTURE_FAIL 1081
#define NO_PICTURES_IN_CHOSEN_DATE 1082

//Manage Users
#define FIND_USER_BY_MAIL 700
#define RAISE_USER_AUTH_BY_ID 701
#define LOWER_USER_AUTH_BY_ID 702
#define RETURN_USER_ID_BY_MAIL 1090
#define RAISE_USER_AUTH_FAIL 1092
#define RAISE_USER_AUTH_SUCCESS 1091
#define LOWER_USER_AUTH_FAIL 1094
#define LOWER_USER_AUTH_SUCCESS 1093

//Schedule
#define GET_SHEDULE 800
#define RETRUN_SCHEDULE 1100
#define RETRUN_SCHEDULE_FAILED 1101

//Ram
#define RAM_IP ""
#define SWIPE 100
#define LEFT_CAMERA 111
#define RIGHT_CAMERA 112
#define CANCEL 211
#define STATUS 10
#define OK 1
#define READY 15
#define BUSY 16
#define PICTURE 20
#define PLANTS 30

//Sagi
#define SAGI_IP ""
#define SENSOR_1_IP ""
#define SENSOR_2_IP ""
#define SENSOR_3_IP ""
#define SENSOR_4_IP ""
#define SENSOR_5_IP ""
#define SENSOR_6_IP ""
#define SENSOR_7_IP ""
#define WATERING_TAPS 6


//Program:
#define APP_CLOSE 299

//Reset Password:
#define RESET_PASSWORD 199
#define RESET_PASSWORD_SUCCESS 1990
#define RESET_PASSWORD_FAIL 1991