#pragma once

//SERVER:
#define PORT 1267

//MSG:
#define MSG_SEPARATOR "###"
#define BUFFER_SIZE 128
#define SERVER_RESPONSE_CODE_SIZE 4

//PROTOCOL:
#define INVALID_CODE 0001
#define NO_CODE 0002
#define FORCED_DISCONNECT 0

//Account:
#define SIGN_IN 200
#define SIGN_UP 201
#define SIGN_OUT 202
#define SIGN_IN_SUCCESS 1020
#define SIGN_IN_FAIL 1030
#define SIGN_IN_FAIL_EMAIL_NOT_REGISTERED 1031
#define SIGN_UP_SUCCESS 1040
#define SIGN_UP_FAIL 1050
#define SIGN_UP_FAIL_PASS_ILLEGAL 1051
#define SIGN_UP_FAIL_EMAIL_INVALID 1052
#define SIGN_UP_FAIL_EMAIL_TAKEN 1053

//Program:
#define APP_CLOSE 299

//Reset Password:
#define RESET_PASSWORD 199
#define RESET_PASSWORD_SUCCESS 1990
#define RESET_PASSWORD_FAIL 1991